[build]
  publish = "."
  command = "cd netlify/functions && npm install"
  functions = "netlify/functions"

# Habilita URLs limpas (sem .html)
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# CORS para as functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[build.environment]
  NODE_VERSION = "18"

# Configuração das Functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
